# Generated by Django 4.1.7 on 2023-03-29 18:44

import core.event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.event.models.event_directory_path),
        ),
    ]
