# Generated by Django 4.1.7 on 2023-04-03 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_event', '0002_event_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-updated']},
        ),
        migrations.AddField(
            model_name='event',
            name='event_data',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 9, 40, 13, 231024, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='event_limit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
