# Generated by Django 4.1.7 on 2023-04-03 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core_event', '0003_alter_event_options_event_event_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
