# Generated by Django 4.1.7 on 2023-04-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_event', '0004_alter_event_event_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_limit',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
