# Generated by Django 4.1.7 on 2023-05-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
