# Generated by Django 4.1.7 on 2023-03-26 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='opertator',
            new_name='operator',
        ),
    ]
