# Generated by Django 4.1.7 on 2023-04-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_board', '0002_rename_opertator_board_operator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-updated']},
        ),
    ]
