# Generated by Django 4.1.7 on 2023-03-29 08:58

import core.account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.account.models.user_directory_path),
        ),
    ]
