# Generated by Django 4.1.7 on 2023-04-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_account', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-updated']},
        ),
    ]
